services:
  website:
    image: ilincuut/my-devops-website:latest
    container_name: my-site
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - database
  
  database:
    image: postgres:15-alpine
    container_name: my-database
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: